### ISSUE TITLE
Updating from varlink 1.1.0 to varlink 7.0.0 auto code generation compile errors

### ISSUE THREAD

**Issue by tasleson** [varlink/rust#18]
Trying to resurrect the idea of using varlink instead of dbus for a project I'm working on.  When I update from varlink 1.1.0 to 7.0.0 I get compiler errors on auto generated code (same error repeated many times):

```
error[E0277]: the trait bound `varlink_api::org_storage_stratis1::Error: std::convert::From<varlink::ErrorKind>` is not satisfied                                           
   --> src/varlink_api/org_storage_stratis1.rs:385:5                                                                                                                        
    |                                                                                                                                                                       
385 | /     fn block_dev_user_info_set(                                                                                                                                     
386 | |         &mut self,                                                                                                                                                  
387 | |         r#pool_uuid: String,                                                                                                                                        
388 | |         r#block_dev_uuid: String,                                                                                                                                   
389 | |         r#user_info: String,                                                                                                                                        
390 | |     ) -> varlink::MethodCall<BlockDevUserInfoSet_Args, BlockDevUserInfoSet_Reply, Error>;                                                                           
    | |_________________________________________________________________________________________^ the trait `std::convert::From<varlink::ErrorKind>` is not implemented for `varlink_api::org_storage_stratis1::Error`
    |                                                                                                                                                                       
    = help: the following implementations were found:                                                                                                                       
              <varlink_api::org_storage_stratis1::Error as std::convert::From<failure::Context<varlink_api::org_storage_stratis1::ErrorKind>>>                              
              <varlink_api::org_storage_stratis1::Error as std::convert::From<serde_json::Error>>                                                                           
              <varlink_api::org_storage_stratis1::Error as std::convert::From<std::io::Error>>                                                                              
              <varlink_api::org_storage_stratis1::Error as std::convert::From<varlink_api::org_storage_stratis1::ErrorKind>>                                                
            and 2 others                                                                                                                                                    
    = note: required because of the requirements on the impl of `std::convert::Into<varlink_api::org_storage_stratis1::Error>` for `varlink::ErrorKind`                     
    = note: required because of the requirements on the impl of `chainerror::ChainErrorFrom<varlink::ErrorKind>` for `varlink_api::org_storage_stratis1::Error`             
    = note: required by `varlink::MethodCall`   
```

If I specify `varlink_generator = "7"` instead of `varlink_generator = "6"` as stated in the docs 
https://docs.rs/varlink/7.0.0/varlink/  I get:

```
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)                                                      
  --> /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/varlink_parser-4.0.0/src/lib.rs:57:9                                                                   
   |                                                                                                                                                                        
55 | mod format;                                                                                                                                                            
   | ----------- not an extern crate passed with `--extern`                                                                                                                 
56 |                                                                                                                                                                        
57 | pub use format::{Format, FormatColored};                                                                                                                               
   |         ^^^^^^                                                                                                                                                         
   |                                                                                                                                                                        
note: this import refers to the module defined here                                                                                                                         
  --> /home/tasleson/.cargo/registry/src/github.com-1ecc6299db9ec823/varlink_parser-4.0.0/src/lib.rs:55:1                                                                   
   |                                                                                                                                                                        
55 | mod format;                                                                                                                                                            
   | ^^^^^^^^^^^                                                                                                                                                            
                                                                                                                                                                            
error: aborting due to previous error                                                                                                                                       
                                                                                                                                                                            
For more information about this error, try `rustc --explain E0658`.                                                                                                         
error: Could not compile `varlink_parser`.  
```
Branch with commits which has 1.1.0 compiling and latest commit to convert over to 7.0.0 failing:
https://github.com/tasleson/stratisd/commits/varlink_ipc

**Comment by tasleson** [comment]
Unable to build master using rust 1.31.1 (stable)

```
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)                                 
  --> varlink_parser/src/lib.rs:55:9                                                                                                                   
   |                                                                                                                                                   
53 | mod format;                                                                                                                                       
   | ----------- not an extern crate passed with `--extern`                                                                                            
54 |                                                                                                                                                   
55 | pub use format::{Format, FormatColored};                                                                                                          
   |         ^^^^^^                                                                                                                                    
   |                                                                                                                                                   
note: this import refers to the module defined here                                                                                                    
  --> varlink_parser/src/lib.rs:53:1                                                                                                                   
   |                                                                                                                                                   
53 | mod format;                                                                                                                                       
   | ^^^^^^^^^^^                                                                                                                                       
                                                                                                                                                       
error: aborting due to previous error                                                                                                                  
                                                                                                                                                       
For more information about this error, try `rustc --explain E0658`.                                                                                    
error: Could not compile `varlink_parser`. 
```

**Comment by haraldh** [comment]
Fixed the `mod format` error with commit aac4782461907023ffade32518ddce2d69470185

**Comment by haraldh** [comment]
Also varlink changed from `failure` Errors to "chainerror" so it will not compile unless you trigger the regeneration of the varlink generated rust code (e.g. by touching the `.varlink` file)
